/**
 * Copyright 2009 Google Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * @fileoverview Interface for JsMin
 */
#include "nsISupports.idl"

/**
 * IJsMin minifies javascript using a C implementation of JsMin.
 *
 * try {
 *   jsmin.minifyJs(input, output);
 * } catch (e) {
 *   // js minify failed.
 * }
 */
[scriptable, uuid(476a1e5e-5c49-4bf7-a8c7-fe23a85c4301)]
interface IJsMin : nsISupports {
  // Minify javascript by running JsMin.
  string minifyJs(in string input);
};
