/**
 * Copyright 2009 Google Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * @fileoverview Interface for the Page Speed rules library.
 *
 * @author Matthew Steele
 */

#include "nsIArray.idl"
#include "nsIDOMDocument.idl"
#include "nsILocalFile.idl"
#include "nsISupports.idl"

/**
 * IPageSpeedRules is the entry point into the Page Speed rules library.
 */
[scriptable, uuid(21ec69bd-f361-4447-b444-1b01b9a17ae3)]
interface IPageSpeedRules : nsISupports {
  const short RESOURCE_FILTER_ALL = 0;
  const short RESOURCE_FILTER_ONLY_ADS = 1;
  const short RESOURCE_FILTER_ONLY_TRACKERS = 2;
  const short RESOURCE_FILTER_ONLY_CONTENT = 3;

  // Run all the rules and return the formatted results as a string.
  AUTF8String computeAndFormatResults(in AUTF8String harData,
                                      in AUTF8String customData,
                                      in nsIArray inputStreams,
                                      in AUTF8String rootUrl,
                                      in nsIDOMDocument rootDocument,
                                      in short filterChoice,
                                      in nsILocalFile outputDir);
};
