/**
 * Copyright 2008-2009 Google Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * @fileoverview IStateStorage is used to share state between Firefox
 * windows.
 *
 * @author Bryan McQuade
 */
#include "nsISupports.idl"

[scriptable, uuid(7a596ebc-9a29-4f0e-8ad9-58d48eb79369)]
interface IStateStorage : nsISupports {
  // No functions exposed via xpcom. All of the code that wants to use
  // this service is in javascript, so we can access the underlying js
  // service object directly.
};
